version: 2

# The configuration for building the documentation
python:
  version: 3.8  # Specify the Python version (adjust as necessary)
  install:
    - requirements: docs/requirements.txt  # Path to your requirements file

# Specify the configuration for Sphinx
sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx configuration file

# Specify the output formats for the documentation
# formats:
#  - html
#  - pdf
#  - epub
